# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FengtianYu_JiayinQi-Ass2-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FengtianYu_JiayinQi-Ass2-ios
	pod 'Firebase/Auth'
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'
	pod 'FirebaseFirestoreSwift'

end
